// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tasks

import (
	"database/sql"
)

type Task struct {
	ID         int64
	Name       string
	CompleteBy sql.NullString
	Completed  sql.NullInt64
}
